[geneva]
nact = 17
img_size_wfs_cam = 124
img_size_fp_cam = 600

npix_small_pupil_grid = 550
nmodes_KL = 289
nmodes_dm = 289

[ohp]
nact = 17

img_size_wfs_cam_x =  240 #160
img_size_wfs_cam_y =  240 #128

img_size_fp_cam_x =  600 #816
img_size_fp_cam_y =  600 #624

npix_small_pupil_grid = 550
nmodes_KL = 195
nmodes_dm = 241