[geneva]
nact = 17
img_size_wfs_cam = 124
img_size_fp_cam = 600

npix_small_pupil_grid = 550
nmodes_KL = 289
nmodes_dm = 289

[ohp]
nact = 17

img_size_wfs_cam_x = 160 #240
img_size_wfs_cam_y = 128 #240

img_size_fp_cam_x = 816 #600
img_size_fp_cam_y = 624 #600

npix_small_pupil_grid = 550
nmodes_KL = 195
nmodes_dm = 241