slopes_image            = '/tmp/slopes_image.im.shm'
phase_screen            = '/tmp/phase_screen.im.shm'
dm_phase                = '/tmp/dm_phase.im.shm'
phase_residuals         = '/tmp/phase_residuals.im.shm'
normalized_psf          = '/tmp/normalized_psf.im.shm'
commands                = '/tmp/commands.im.shm'
residual_modes          = '/tmp/residual_modes.im.shm'
computed_modes           = '/tmp/computed_modes.im.shm'
dm_kl_modes              = '/tmp/dm_kl_modes.im.shm'
norm_flux_pyr_img        = '/tmp/norm_flux_pyr_img.im.shm'


small_pupil_mask        = '/tmp/small_pupil_mask.im.shm'
pupil_mask              = '/tmp/pupil_mask.im.shm'
slopes_img              = '/tmp/slopes_img.im.shm'
dm_act                  = '/tmp/dm_act.im.shm'
slm                     = '/tmp/slm.im.shm'
Act2Phs                 = '/tmp/Act2Phs.im.shm'
Phs2Act                 = '/tmp/Phs2Act.im.shm'
KL2Act                  = '/tmp/KL2Act.im.shm'
Act2KL                  = '/tmp/Act2KL.im.shm'
KL2Phs                  = '/tmp/KL2Phs.im.shm'
Phs2KL                  = '/tmp/Phs2KL.im.shm'
Znk2Act                 = '/tmp/Znk2Act.im.shm'
Act2Znk                 = '/tmp/Act2Znk.im.shm'
Znk2Phs                 = '/tmp/Znk2Phs.im.shm'
Phs2Znk                 = '/tmp/Phs2Znk.im.shm'
valid_pixels_mask       = '/tmp/valid_pixels_mask.im.shm'
bias_image              = '/tmp/bias_image.im.shm'
reference_psf           = '/tmp/reference_psf.im.shm'
normalized_ref_psf      = '/tmp/normalized_ref_psf.im.shm'
reference_image         = '/tmp/reference_image.im.shm'
normalized_ref_image    = '/tmp/normalized_ref_image.im.shm'
npix_valid              = '/tmp/npix_valid.im.shm'
KL2PWFS_cube            = '/tmp/KL2PWFS_cube.im.shm'
slopes                  = '/tmp/slopes.im.shm'
KL2S                    = '/tmp/KL2S.im.shm'
S2KL                    = '/tmp/S2KL.im.shm'

delay_set               = '/tmp/delay_set.im.shm'             
gain                     = '/tmp/gain.im.shm'                
leakage                  = '/tmp/leakage.im.shm'             
num_iterations           = '/tmp/num_iterations.im.shm'
cam1 = '/tmp/cam1.im.shm'
cam2 = '/tmp/cam2.im.shm'
cam1Fps                 = '/tmp/cam1Fps.im.shm'
cam2Fps                 = '/tmp/cam2Fps.im.shm'


KL2Act_papy = '/tmp/m2c.im.shm'



