
[control]
modes_buf = '/tmp/modes_buf.shm'
commands_buf = '/tmp/commands_buf.shm'
pol_buf = '/tmp/pol_buf.shm'
t = '/tmp/t.shm'

state_mat = '/tmp/state_mat.shm'
K_mat_int = '/tmp/K_mat_int.shm'
K_mat_dd = '/tmp/K_mat_dd.shm'
K_mat_omgi = '/tmp/K_mat_omgi.shm'

modes_fft = '/tmp/modes_fft.shm'
commands_fft = '/tmp/commands_fft.shm'
pol_fft = '/tmp/pol_fft.shm'
f = '/tmp/f.shm'

latency = '/tmp/latency.shm'
fs = '/tmp/fs.shm'
delay = '/tmp/delay.shm'

closed_loop_flag = '/tmp/closed_loop_flag.shm'
controller_select = '/tmp/controller_select.shm'
n_modes_dd_high = '/tmp/n_modes_dd_high.shm'
n_modes_dd_low = '/tmp/n_modes_dd_low.shm'
n_modes_int = '/tmp/n_modes_int.shm'

dd_update_rate_high = '/tmp/dd_update_rate_high.shm'
dd_update_rate_low = '/tmp/dd_update_rate_low.shm'

dd_order_high = '/tmp/dd_order_high.shm'
dd_order_low = '/tmp/dd_order_low.shm'

gain_margin = '/tmp/gain_margin.shm'

n_fft = '/tmp/n_fft.shm'

wait_time = '/tmp/wait_time.shm'

record_time = '/tmp/record_time.shm'

S_dd = '/tmp/S_dd.shm'
S_omgi = '/tmp/S_omgi.shm'
S_int = '/tmp/S_int.shm'
f_opti = '/tmp/f_opti.shm'

mutex_opti = '/tmp/mutex_opti.shm'
slopes = '/tmp/papyrus_slopes.im.shm'
S2M = '/tmp/S2M.shm'
reset_flag = '/tmp/reset_flag.shm'

telemetry = '/tmp/telemetry.shm'

# modes = '/tmp/modes.shm'
modes = '/tmp/papyrus_modes.im.shm'
dm = '/tmp/dmCmd02.im.shm' 
M2V = '/tmp/m2c.im.shm'

# modes = '/tmp/computed_modes.im.shm'
# dm = '/tmp/dm_act.im.shm'
# M2V = '/tmp/KL2Act.im.shm'

flat_dm = '/tmp/dmCmd00.im.shm'
