slopes_image            = '/tmp/slopes_image.im.shm'
phase_screen            = '/tmp/phase_screen.im.shm'
dm_phase                = '/tmp/dm_phase.im.shm'
phase_residuals         = '/tmp/phase_residuals.im.shm'
normalized_psf          = '/tmp/normalized_psf.im.shm'
commands                = '/tmp/commands.im.shm'
residual_modes          = '/tmp/residual_modes.im.shm'
computed_modes           = '/tmp/computed_modes.im.shm'
dm_kl_modes              = '/tmp/dm_kl_modes.im.shm'
norm_flux_pyr_img        = '/tmp/norm_flux_pyr_img.im.shm'
strehl_ratio             = '/tmp/strehl_ratio.im.shm'


# small_pupil_mask        = '/tmp/small_pupil_mask.im.shm'
# pupil_mask              = '/tmp/pupil_mask.im.shm'
dm_act                  = '/tmp/dm_act.im.shm'
slm                     = '/tmp/slm.im.shm'

KL2Act                  = '/tmp/KL2Act.im.shm'
Act2KL                  = '/tmp/Act2KL.im.shm'
# KL2Phs                  = '/tmp/KL2Phs.im.shm'
# Phs2KL                  = '/tmp/Phs2KL.im.shm'

valid_pixels_mask       = '/tmp/valid_pixels_mask.im.shm'
reference_psf           = '/tmp/reference_psf.im.shm'
normalized_ref_psf      = '/tmp/normalized_ref_psf.im.shm'
reference_image         = '/tmp/reference_image.im.shm'
normalized_ref_image    = '/tmp/normalized_ref_image.im.shm'
npix_valid              = '/tmp/npix_valid.im.shm'
KL2PWFS_cube            = '/tmp/KL2PWFS_cube.im.shm'
slopes                  = '/tmp/slopes.im.shm'
KL2S                    = '/tmp/KL2S.im.shm'
S2KL                    = '/tmp/S2KL.im.shm'

delay_set               = '/tmp/delay_set.im.shm'             
gain                     = '/tmp/gain.im.shm'                
leakage                  = '/tmp/leakage.im.shm'             
num_iterations           = '/tmp/num_iterations.im.shm'


cam1 = '/tmp/cred3_cropped.im.shm' #'/tmp/cred3.im.shm'#'/tmp/ocam2.im.shm' #'/tmp/cam1.im.shm'
cam2 = '/tmp/cblue.im.shm'#'/tmp/cam2.im.shm'
cam1Fps                 = '/tmp/cred3Fps.im.shm' #'/tmp/cam1Fps.im.shm'
cam2Fps                 = '/tmp/cblueFps.im.shm' #'/tmp/cam2Fps.im.shm'



#KL modes for papyrus
KL2Act_papy = '/tmp/m2c.im.shm'

# shared memory to send commands to the DM papyrus
dm_papy = '/tmp/dmCmd02.im.shm'

#shared memory to set the dm flat for papyrus
dm_flat_papy = '/tmp/dmCmd03.im.shm'

# shared memory with the map of valid actuators for papyrus
dm_map = '/tmp/dm241Map.im.shm'




