slopes_image            = '/tmp/slopes_image.im.shm'            
phase_screen            = '/tmp/phase_screen.im.shm'            
dm_phase                = '/tmp/dm_phase.im.shm'                
phase_residuals         = '/tmp/phase_residuals.im.shm'        
normalized_psf          = '/tmp/normalized_psf.im.shm'       
commands                = '/tmp/commands.im.shm'              
residual_modes          = '/tmp/residual_modes.im.shm'          
computed_modes           = '/tmp/computed_modes.im.shm'         
dm_kl_modes              = '/tmp/dm_kl_modes.im.shm' 


delay                    = '/tmp/delay.im.shm'             
gain                     = '/tmp/gain.im.shm'                
leakage                  = '/tmp/leakage.im.shm'             
num_iterations           = '/tmp/num_iterations.im.shm'
cam1 = '/tmp/cam1.im.shm'
cam2 = '/tmp/cam2.im.shm'
