camera_wfs = '/tmp/cam1.im.shm'
camera_fp = '/tmp/cam2.im.shm'
fps_wfs = '/tmp/cam1Fps.im.shm'
fps_fp = '/tmp/cam2Fps.im.shm'
slm = '/tmp/slm.im.shm'

closed_loop_flag = '/tmp/closed_loop_flag.shm'
n_modes_int = '/tmp/n_modes_int.shm'
record_time = '/tmp/record_time.shm'

slopes_m_buf = '/tmp/slopes_m_buf.shm'
commands_m_buf = '/tmp/commands_m_buf.shm'
pol_m_buf = '/tmp/pol_m_buf.shm'


slopes_image_shm             = '/tmp/slopes_image.im.shm'            
phase_screen_shm             = '/tmp/phase_screen.im.shm'            
dm_phase_shm                 = '/tmp/dm_phase.im.shm'                
phase_residuals_shm          = '/tmp/phase_residuals.im.shm'        
normalized_psf_shm           = '/tmp/normalized_psf.im.shm'       
commands_shm                 = '/tmp/commands.im.shm'              
residual_modes_shm           = '/tmp/residual_modes.im.shm'          
computed_modes_shm           = '/tmp/computed_modes.im.shm'         
dm_kl_modes_shm              = '/tmp/dm_kl_modes.im.shm' 